---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: testv2.azurecr.io/rabbitmq:v2
        ports:
        - name: gui
          containerPort: 15672
        - name: service
          containerPort: 5672
      imagePullSecrets:
      - name: acr-auth
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: gui
    port: 15672
    targetPort: 15672
  - name: service
    port: 5672
    targetPort: 5672    
  selector:
    app: rabbitmq
  type: LoadBalancer