---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      name: helloworld
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: nenad.azurecr.io/helloworld:#{Version}#
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets: Always
      - name: ascreg
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    name: helloworld
  type: LoadBalancer